language: fish
before_install:
    - sudo apt-add-repository ppa:fish-shell/release-2 -y
    - sudo apt-get -q update
    - sudo apt-get install -y fish
    - git clone git://github.com/terlar/fish-tank.git
script: fish tests/runner.fish
env:
    - FISH_TANK="$PWD/fish-tank"
